import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import {HttpClient} from "@angular/common/http";
import {ForumPage} from "../forum/forum";

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  public courses: Array<{title: string, author: string, forums: {"title": string, "subtitle": string, "discussions": string[], "description": string}[]}> = [];
  public items: Array<{expanded: boolean, icon: string}> = [];
  public itemExpandHeight: number = 45;

  // private url: string = 'https://jsonplaceholder.typicode.com';
  // public c: any;

  constructor(public navCtrl: NavController,
              public http: HttpClient) {
    this.courses.push({"title": "course_1", "author": "author_1", "forums": [{
                                                                              "title": "first",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "second",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "third",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "fourth",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            }
                                                                            ]});
    this.courses.push({"title": "course_2", "author": "author_1", "forums": [{
                                                                              "title": "first",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "second",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "third",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "fourth",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            }
                                                                            ]});
    this.courses.push({"title": "course_2", "author": "author_1", "forums": [{
                                                                              "title": "first",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "second",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "third",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "fourth",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            }
                                                                            ]});
    this.courses.push({"title": "course_2", "author": "author_1", "forums": [{
                                                                              "title": "first",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "second",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "third",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae ex bibendum, rutrum erat at, tincidunt diam. Etiam lectus arcu, pharetra id tortor quis, dapibus faucibus massa. Fusce rhoncus urna ut odio aliquam, ut dignissim velit hendrerit. Aenean ut dolor vitae tortor dictum hendrerit vel et risus. Praesent sed mattis quam. Proin pretium vehicula sapien eget vulputate. Proin in iaculis nibh. Sed ultricies, dui eu dapibus sollicitudin, felis elit viverra nisl, ultricies semper nunc tortor at sem.\n" +
                                                                              "\n" +
                                                                              "Nunc ac ligula velit. Nunc sollicitudin tortor in luctus tempor. Vivamus gravida faucibus vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas mattis, sapien ut auctor condimentum, eros nisl vehicula metus, non lobortis leo massa id ligula. Aliquam orci mi, posuere eget ex eu, ullamcorper mollis erat. Donec sed lacus vel massa aliquam aliquam id eu nibh. Vivamus molestie, lectus in auctor bibendum, justo quam pharetra justo, eget finibus arcu nulla ut lacus. Nullam viverra, quam ut venenatis feugiat, lorem turpis lobortis odio, quis gravida mi mi id justo.\n" +
                                                                              "\n" +
                                                                              "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur rhoncus turpis ornare finibus. Morbi non eros id nulla convallis convallis. Etiam efficitur enim sit amet lacus posuere dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et neque laoreet, euismod nibh eu, rhoncus ex. Duis augue lectus, vehicula tempus lobortis ut, elementum id tortor. Duis nec ante odio. Nam vestibulum, odio ut luctus maximus, libero nisl blandit quam, sit amet egestas ipsum libero consectetur velit. Quisque id turpis non diam tempor tempor at et est.\n" +
                                                                              "\n" +
                                                                              "Integer tincidunt eget libero nec rhoncus. Praesent finibus viverra ligula laoreet fermentum. Aliquam a euismod elit. Cras vel orci pretium, sollicitudin libero vel, aliquet ante. Suspendisse mi tellus, malesuada sed condimentum vel, malesuada eu libero. Morbi ac semper lectus. Duis vestibulum, quam et euismod porta, nunc turpis elementum nisi, quis blandit enim libero ut erat. Etiam semper, ex id rhoncus tristique, sapien sapien ultricies elit, in sagittis ex libero quis eros. Mauris vel tortor odio. Aliquam gravida nisl in nisl blandit suscipit. In non nisl quis nibh tincidunt facilisis. Pellentesque turpis est, mollis quis placerat efficitur, pretium sed velit. Vivamus consectetur arcu eget velit ultrices interdum. Proin ullamcorper commodo tortor eget finibus.\n" +
                                                                              "\n" +
                                                                              "Nam congue libero non ligula sodales tincidunt. Maecenas malesuada non dui eget suscipit. In hac habitasse platea dictumst. Suspendisse erat metus, ultrices eget porta sit amet, sodales in augue. Fusce sagittis quam quis nulla aliquam venenatis. Mauris fringilla ultricies aliquet. Morbi at faucibus arcu."
                                                                            },
                                                                            {
                                                                              "title": "fourth",
                                                                              "subtitle": "some subtitle",
                                                                              "discussions": ["discussion_1", "discussion_2", "discussion_3", "discussion_4"],
                                                                              "description": "Lorem ipsum dolor sit amet, "
                                                                            }
                                                                            ]});
    let qtdItems;

    qtdItems = this.courses.length;
    this.itemExpandHeight *= qtdItems;

    // this.http.get(this.url + '/users')
    //   .subscribe(data => {
    //     this.c = data;
    //     qtdItems = this.c.length;
    //     console.log('here: ' + this.c.length);
    //     for(let i in this.c) {
    //       console.log(i);
    //     }
    //   });

    for(let i = 0; i < qtdItems; i++) {
      this.items.push({'expanded': false, 'icon': 'arrow-dropdown'});
    }

  }

  expandItem(item){
    this.items.map((listItem) => {

      if(item == listItem){
        listItem.expanded = !listItem.expanded;
        listItem.expanded ? listItem.icon = 'arrow-dropup' : listItem.icon = 'arrow-dropdown';
      } else {
        listItem.expanded = false;
        listItem.icon = 'arrow-dropdown';
      }

      return listItem;

    });
  }

  goToForum(forum) {
    this.navCtrl.push(ForumPage,
      {
        'forum': forum
      });
  }

}
